version: "3.8"
services:
  app:
    image: ml-backend-assignment:dev
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
